/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designbosco;

import static designbosco.JFramePrincipal.chequearSiEsEntero;
import static designbosco.JFramePrincipal.sistema;
import java.awt.Color;

/**
 *
 * @author Ezequiel Melogno
 */
public class JFrameLocal extends javax.swing.JFrame {
    
    static int index;
    
    public JFrameLocal(int index) {
        initComponents();
        JFrameLocal.index = index;
        departamento.setSelectedIndex(JFramePrincipal.sistema.getLocal(index).getDepartamento());
        ciudad.setText(JFramePrincipal.sistema.getLocal(index).getCiudad());
        direccion.setText(JFramePrincipal.sistema.getLocal(index).getDireccion());
        actualizarListaEmpleados();
        actualizarListaEquipos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localTab = new javax.swing.JTabbedPane();
        local = new javax.swing.JPanel();
        direccion_text = new javax.swing.JLabel();
        departamento_text = new javax.swing.JLabel();
        ciudad_text = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        guardarDireccion = new javax.swing.JButton();
        departamento = new javax.swing.JComboBox<>();
        ciudad = new javax.swing.JTextField();
        guardarDepartamento = new javax.swing.JButton();
        guardarCiudad = new javax.swing.JButton();
        cambios_text = new javax.swing.JLabel();
        empleados = new javax.swing.JPanel();
        listaEmpleadosContainer = new javax.swing.JScrollPane();
        listaEmpleados = new javax.swing.JList<>();
        empleados_text = new javax.swing.JLabel();
        anadirEmpleado = new javax.swing.JButton();
        eliminarEmpleado = new javax.swing.JButton();
        editarEmpleado = new javax.swing.JButton();
        nombreEmpleado = new javax.swing.JTextField();
        nombreEmpleado_text = new javax.swing.JLabel();
        anadirCliente_text = new javax.swing.JLabel();
        apellidoEmpleado_text = new javax.swing.JLabel();
        apellidoEmpleado = new javax.swing.JTextField();
        ciEmpleado = new javax.swing.JTextField();
        ciEmpleado_text = new javax.swing.JLabel();
        telefonoEmpleado_text = new javax.swing.JLabel();
        telefonoEmpleado = new javax.swing.JTextField();
        correoEmpleado = new javax.swing.JTextField();
        correoEmpleado_text = new javax.swing.JLabel();
        empleadoDarDeAlta = new javax.swing.JLabel();
        verEmpleado = new javax.swing.JButton();
        actualizarListaEmpleados = new javax.swing.JButton();
        cargoEmpleado_text = new javax.swing.JLabel();
        cargoEmpleado = new javax.swing.JTextField();
        buscarEmpleado = new javax.swing.JButton();
        equipos = new javax.swing.JPanel();
        listaEquiposContainer = new javax.swing.JScrollPane();
        listaEquipos = new javax.swing.JList<>();
        equipos_text = new javax.swing.JLabel();
        anadirEquipo = new javax.swing.JButton();
        eliminarEquipo = new javax.swing.JButton();
        editarEquipo = new javax.swing.JButton();
        sistemaOperativoEquipo = new javax.swing.JTextField();
        nombreEmpleado_text1 = new javax.swing.JLabel();
        anadirEquipo_text = new javax.swing.JLabel();
        telefonoEmpleado_text1 = new javax.swing.JLabel();
        plantaEquipo = new javax.swing.JTextField();
        habitacionEquipo = new javax.swing.JTextField();
        correoEmpleado_text1 = new javax.swing.JLabel();
        equipoDarDeAlta = new javax.swing.JLabel();
        verEquipo = new javax.swing.JButton();
        actualizarListaEquipos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(JFramePrincipal.sistema.getLocal(index).toString());
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        localTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        localTab.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        localTab.setMinimumSize(new java.awt.Dimension(800, 600));

        local.setBackground(new java.awt.Color(255, 255, 255));
        local.setMinimumSize(new java.awt.Dimension(800, 600));
        local.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        direccion_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        direccion_text.setText("Direccion:");
        local.add(direccion_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, 20));

        departamento_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        departamento_text.setText("Departamento:");
        local.add(departamento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 20));

        ciudad_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        ciudad_text.setText("Ciudad:");
        local.add(ciudad_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, 20));

        direccion.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        local.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 300, 20));

        guardarDireccion.setBackground(new java.awt.Color(255, 255, 255));
        guardarDireccion.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarDireccion.setText("Guardar");
        guardarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDireccionActionPerformed(evt);
            }
        });
        local.add(guardarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 80, 20));

        departamento.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Elige un departamento*", "Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", "Flores", "Florida", "Lavalleja", "Maldonado", "Montevideo", "Paysandu", "Rio Negro", "Rivera", "Rocha", "Salto", "San Jose", "Soriano", "Tacuarembo", "Treinta y Tres" }));
        local.add(departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 300, 20));

        ciudad.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });
        local.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 300, 20));

        guardarDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        guardarDepartamento.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarDepartamento.setText("Guardar");
        guardarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDepartamentoActionPerformed(evt);
            }
        });
        local.add(guardarDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 80, 20));

        guardarCiudad.setBackground(new java.awt.Color(255, 255, 255));
        guardarCiudad.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarCiudad.setText("Guardar");
        guardarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCiudadActionPerformed(evt);
            }
        });
        local.add(guardarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 80, 20));

        cambios_text.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        local.add(cambios_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 500, 50));

        localTab.addTab("Local", local);

        empleados.setBackground(new java.awt.Color(255, 255, 255));
        empleados.setMinimumSize(new java.awt.Dimension(800, 600));
        empleados.setPreferredSize(new java.awt.Dimension(800, 600));
        empleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaEmpleadosContainer.setViewportView(listaEmpleados);

        empleados.add(listaEmpleadosContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 260, 490));

        empleados_text.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        empleados_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empleados_text.setText("Empleados");
        empleados.add(empleados_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 260, 34));

        anadirEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        anadirEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        anadirEmpleado.setText("Anadir");
        anadirEmpleado.setActionCommand("");
        anadirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirEmpleadoActionPerformed(evt);
            }
        });
        empleados.add(anadirEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 230, -1));

        eliminarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        eliminarEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        eliminarEmpleado.setText("Eliminar");
        eliminarEmpleado.setActionCommand("");
        eliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpleadoActionPerformed(evt);
            }
        });
        empleados.add(eliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        editarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        editarEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        editarEmpleado.setText("Editar");
        editarEmpleado.setActionCommand("");
        editarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEmpleadoActionPerformed(evt);
            }
        });
        empleados.add(editarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 85, -1));
        empleados.add(nombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, -1));

        nombreEmpleado_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        nombreEmpleado_text.setText("Nombre");
        empleados.add(nombreEmpleado_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        anadirCliente_text.setBackground(new java.awt.Color(255, 255, 255));
        anadirCliente_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        anadirCliente_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirCliente_text.setText("Anadir Empleado");
        empleados.add(anadirCliente_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, -1));

        apellidoEmpleado_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        apellidoEmpleado_text.setText("Apellido");
        empleados.add(apellidoEmpleado_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        empleados.add(apellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, -1));
        empleados.add(ciEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 230, -1));

        ciEmpleado_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        ciEmpleado_text.setText("Cedula de identidad");
        empleados.add(ciEmpleado_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        telefonoEmpleado_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        telefonoEmpleado_text.setText("Telefono");
        empleados.add(telefonoEmpleado_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        empleados.add(telefonoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 230, -1));
        empleados.add(correoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 230, -1));

        correoEmpleado_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        correoEmpleado_text.setText("Correo electronico");
        empleados.add(correoEmpleado_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        empleadoDarDeAlta.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        empleadoDarDeAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empleados.add(empleadoDarDeAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 230, 80));

        verEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        verEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        verEmpleado.setText("Ver");
        verEmpleado.setActionCommand("");
        verEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEmpleadoActionPerformed(evt);
            }
        });
        empleados.add(verEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 85, -1));

        actualizarListaEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        actualizarListaEmpleados.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        actualizarListaEmpleados.setText("Actualizar");
        actualizarListaEmpleados.setActionCommand("");
        actualizarListaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarListaEmpleadosActionPerformed(evt);
            }
        });
        empleados.add(actualizarListaEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        cargoEmpleado_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        cargoEmpleado_text.setText("Cargo");
        empleados.add(cargoEmpleado_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        empleados.add(cargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 230, -1));

        buscarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        buscarEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        buscarEmpleado.setText("Buscar");
        buscarEmpleado.setActionCommand("");
        buscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmpleadoActionPerformed(evt);
            }
        });
        empleados.add(buscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 85, -1));

        localTab.addTab("Empleados", empleados);

        equipos.setBackground(new java.awt.Color(255, 255, 255));
        equipos.setMinimumSize(new java.awt.Dimension(800, 600));
        equipos.setPreferredSize(new java.awt.Dimension(800, 600));
        equipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaEquiposContainer.setViewportView(listaEquipos);

        equipos.add(listaEquiposContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 260, 490));

        equipos_text.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        equipos_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipos_text.setText("Equipos");
        equipos.add(equipos_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 260, 34));

        anadirEquipo.setBackground(new java.awt.Color(255, 255, 255));
        anadirEquipo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        anadirEquipo.setText("Anadir");
        anadirEquipo.setActionCommand("");
        anadirEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirEquipoActionPerformed(evt);
            }
        });
        equipos.add(anadirEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, -1));

        eliminarEquipo.setBackground(new java.awt.Color(255, 255, 255));
        eliminarEquipo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        eliminarEquipo.setText("Eliminar");
        eliminarEquipo.setActionCommand("");
        eliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEquipoActionPerformed(evt);
            }
        });
        equipos.add(eliminarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        editarEquipo.setBackground(new java.awt.Color(255, 255, 255));
        editarEquipo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        editarEquipo.setText("Editar");
        editarEquipo.setActionCommand("");
        editarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEquipoActionPerformed(evt);
            }
        });
        equipos.add(editarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 85, -1));
        equipos.add(sistemaOperativoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, -1));

        nombreEmpleado_text1.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        nombreEmpleado_text1.setText("Sistema Operativo");
        equipos.add(nombreEmpleado_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        anadirEquipo_text.setBackground(new java.awt.Color(255, 255, 255));
        anadirEquipo_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        anadirEquipo_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirEquipo_text.setText("Anadir Equipo");
        equipos.add(anadirEquipo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, -1));

        telefonoEmpleado_text1.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        telefonoEmpleado_text1.setText("Numero de Planta");
        equipos.add(telefonoEmpleado_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        equipos.add(plantaEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, -1));
        equipos.add(habitacionEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 230, -1));

        correoEmpleado_text1.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        correoEmpleado_text1.setText("Numero de Habitacion");
        equipos.add(correoEmpleado_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        equipoDarDeAlta.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        equipoDarDeAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipos.add(equipoDarDeAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 230, 80));

        verEquipo.setBackground(new java.awt.Color(255, 255, 255));
        verEquipo.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        verEquipo.setText("Ver");
        verEquipo.setActionCommand("");
        verEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEquipoActionPerformed(evt);
            }
        });
        equipos.add(verEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 85, -1));

        actualizarListaEquipos.setBackground(new java.awt.Color(255, 255, 255));
        actualizarListaEquipos.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        actualizarListaEquipos.setText("Actualizar");
        actualizarListaEquipos.setActionCommand("");
        actualizarListaEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarListaEquiposActionPerformed(evt);
            }
        });
        equipos.add(actualizarListaEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        localTab.addTab("Equipos", equipos);

        getContentPane().add(localTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed

    }//GEN-LAST:event_direccionActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed

    }//GEN-LAST:event_ciudadActionPerformed

    private void guardarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDepartamentoActionPerformed
        if (departamento.getSelectedIndex() == 0) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("Falta elegir depatamento.");
        } else {
            JFramePrincipal.sistema.getLocal(index).setDepartamento(departamento.getSelectedIndex());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Departamento cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarDepartamentoActionPerformed

    private void guardarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCiudadActionPerformed
        if(ciudad.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("La ciudad no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getLocal(index).setCiudad(ciudad.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Ciudad cambiada satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarCiudadActionPerformed

    private void guardarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDireccionActionPerformed
        if(direccion.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("La direccion no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getLocal(index).setDireccion(direccion.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Direccion cambiada satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarDireccionActionPerformed

    
    private void actualizarListaEmpleados() {
        listaEmpleados.setModel(sistema.getLocal(index).getEmpleadoModel());
    }
    
    private void anadirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirEmpleadoActionPerformed
        if(nombreEmpleado.getText().isBlank() ||
            apellidoEmpleado.getText().isBlank() ||
            telefonoEmpleado.getText().isBlank() ||
            ciEmpleado.getText().isBlank() ||
            correoEmpleado.getText().isBlank() ) {
            empleadoDarDeAlta.setForeground(Color.RED);
            empleadoDarDeAlta.setText("Faltan campos para rellenar.");
        } else if (sistema.getLocal(index).verificarEmpleado(ciEmpleado.getText())) {
            empleadoDarDeAlta.setForeground(Color.RED);
            empleadoDarDeAlta.setText("Este Empleado ya existe.");
        } else {
            sistema.getLocal(index).addEmpleado(new Empleado(nombreEmpleado.getText(),apellidoEmpleado.getText(),ciEmpleado.getText(),cargoEmpleado.getText(),correoEmpleado.getText(),telefonoEmpleado.getText()));
            actualizarListaEmpleados();
            empleadoDarDeAlta.setForeground(Color.BLACK);
            empleadoDarDeAlta.setText("Empleado anadido con exito.");
        }
    }//GEN-LAST:event_anadirEmpleadoActionPerformed

    private void eliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpleadoActionPerformed
        if(listaEmpleados.getSelectedIndex() > -1) {
            sistema.getLocal(index).removeEmpleado(listaEmpleados.getSelectedIndex());
            actualizarListaEmpleados();
        }
    }//GEN-LAST:event_eliminarEmpleadoActionPerformed

    private void editarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEmpleadoActionPerformed
        if(listaEmpleados.getSelectedIndex() > -1) {
            new JFrameEmpleado(index, listaEmpleados.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_editarEmpleadoActionPerformed

    private void verEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEmpleadoActionPerformed
        if(listaEmpleados.getSelectedIndex() > -1) {
            new JFrameEmpleado(index, listaEmpleados.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_verEmpleadoActionPerformed

    private void actualizarListaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarListaEmpleadosActionPerformed
        actualizarListaEmpleados();
    }//GEN-LAST:event_actualizarListaEmpleadosActionPerformed

    
    private void actualizarListaEquipos() {
        listaEquipos.setModel(sistema.getLocal(index).getEquipoModel());
    }
    
    private void anadirEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirEquipoActionPerformed
        if(sistemaOperativoEquipo.getText().isBlank() ||
        plantaEquipo.getText().isBlank() ||
        habitacionEquipo.getText().isBlank() ) {
            equipoDarDeAlta.setForeground(Color.RED);
            equipoDarDeAlta.setText("Faltan campos para rellenar.");
        } else if (!chequearSiEsEntero(plantaEquipo.getText())) {
            equipoDarDeAlta.setForeground(Color.RED);
            equipoDarDeAlta.setText("La planta tiene que ser un entero.");
        } else if (!chequearSiEsEntero(habitacionEquipo.getText())) {
            equipoDarDeAlta.setForeground(Color.RED);
            equipoDarDeAlta.setText("La habitacion tiene que ser un entero.");
        } else {
            JFramePrincipal.sistema.getLocal(index).addEquipo(new Equipo(sistemaOperativoEquipo.getText(), Integer.valueOf(plantaEquipo.getText()), Integer.valueOf(habitacionEquipo.getText())));
            actualizarListaEquipos();
            equipoDarDeAlta.setForeground(Color.BLACK);
            equipoDarDeAlta.setText("Equipo anadido satisfactioriamente.");
        }
    }//GEN-LAST:event_anadirEquipoActionPerformed

    private void eliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEquipoActionPerformed
        if(listaEquipos.getSelectedIndex() > -1) {
            JFramePrincipal.sistema.getLocal(index).removeEquipo(listaEquipos.getSelectedIndex());
        actualizarListaEquipos();
        }
    }//GEN-LAST:event_eliminarEquipoActionPerformed

    private void editarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEquipoActionPerformed
        if(listaEquipos.getSelectedIndex() > -1) {
            new JFrameEquipo(index, listaEquipos.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_editarEquipoActionPerformed

    private void verEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEquipoActionPerformed
        if(listaEquipos.getSelectedIndex() > -1) {
            new JFrameEquipo(index, listaEquipos.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_verEquipoActionPerformed

    private void actualizarListaEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarListaEquiposActionPerformed
        actualizarListaEquipos();
    }//GEN-LAST:event_actualizarListaEquiposActionPerformed

    private void buscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmpleadoActionPerformed
        new JFrameBuscarEmpleado(index).setVisible(true);
    }//GEN-LAST:event_buscarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarListaEmpleados;
    private javax.swing.JButton actualizarListaEquipos;
    private javax.swing.JLabel anadirCliente_text;
    private javax.swing.JButton anadirEmpleado;
    private javax.swing.JButton anadirEquipo;
    private javax.swing.JLabel anadirEquipo_text;
    private javax.swing.JTextField apellidoEmpleado;
    private javax.swing.JLabel apellidoEmpleado_text;
    private javax.swing.JButton buscarEmpleado;
    private javax.swing.JLabel cambios_text;
    private javax.swing.JTextField cargoEmpleado;
    private javax.swing.JLabel cargoEmpleado_text;
    private javax.swing.JTextField ciEmpleado;
    private javax.swing.JLabel ciEmpleado_text;
    private javax.swing.JTextField ciudad;
    private javax.swing.JLabel ciudad_text;
    private javax.swing.JTextField correoEmpleado;
    private javax.swing.JLabel correoEmpleado_text;
    private javax.swing.JLabel correoEmpleado_text1;
    private javax.swing.JComboBox<String> departamento;
    private javax.swing.JLabel departamento_text;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccion_text;
    private javax.swing.JButton editarEmpleado;
    private javax.swing.JButton editarEquipo;
    private javax.swing.JButton eliminarEmpleado;
    private javax.swing.JButton eliminarEquipo;
    private javax.swing.JLabel empleadoDarDeAlta;
    private javax.swing.JPanel empleados;
    private javax.swing.JLabel empleados_text;
    private javax.swing.JLabel equipoDarDeAlta;
    private javax.swing.JPanel equipos;
    private javax.swing.JLabel equipos_text;
    private javax.swing.JButton guardarCiudad;
    private javax.swing.JButton guardarDepartamento;
    private javax.swing.JButton guardarDireccion;
    private javax.swing.JTextField habitacionEquipo;
    private javax.swing.JList<String> listaEmpleados;
    private javax.swing.JScrollPane listaEmpleadosContainer;
    private javax.swing.JList<String> listaEquipos;
    private javax.swing.JScrollPane listaEquiposContainer;
    private javax.swing.JPanel local;
    private javax.swing.JTabbedPane localTab;
    private javax.swing.JTextField nombreEmpleado;
    private javax.swing.JLabel nombreEmpleado_text;
    private javax.swing.JLabel nombreEmpleado_text1;
    private javax.swing.JTextField plantaEquipo;
    private javax.swing.JTextField sistemaOperativoEquipo;
    private javax.swing.JTextField telefonoEmpleado;
    private javax.swing.JLabel telefonoEmpleado_text;
    private javax.swing.JLabel telefonoEmpleado_text1;
    private javax.swing.JButton verEmpleado;
    private javax.swing.JButton verEquipo;
    // End of variables declaration//GEN-END:variables
}
