/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designbosco;

import static designbosco.JFramePrincipal.sistema;
import java.awt.Color;

/**
 *
 * @author Ezequiel Melogno
 */
public class JFrameCliente extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCliente
     */
    
    static int index;
    
    public JFrameCliente(int index) {
        initComponents();
        JFrameCliente.index = index;
        nombreCliente.setText(JFramePrincipal.sistema.getCliente(index).getNombre());
        apellidoCliente.setText(JFramePrincipal.sistema.getCliente(index).getApellido());
        ciCliente.setText(JFramePrincipal.sistema.getCliente(index).getCi());
        telefonoCliente.setText(JFramePrincipal.sistema.getCliente(index).getTelefono());
        correoCliente.setText(JFramePrincipal.sistema.getCliente(index).getCorreo());
        productos.setModel(JFramePrincipal.sistema.getProductoComboBoxModel());
        actualizarListaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productosComprados_text = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        guardarNombre = new javax.swing.JButton();
        apellido_text = new javax.swing.JLabel();
        apellidoCliente = new javax.swing.JTextField();
        guardarApellido = new javax.swing.JButton();
        ciCliente = new javax.swing.JTextField();
        guardarCi = new javax.swing.JButton();
        ci_text = new javax.swing.JLabel();
        guardarTelefono = new javax.swing.JButton();
        telefono_text = new javax.swing.JLabel();
        telefonoCliente = new javax.swing.JTextField();
        correo_text = new javax.swing.JLabel();
        guardarCorreo = new javax.swing.JButton();
        correoCliente = new javax.swing.JTextField();
        registrarCompra_text = new javax.swing.JLabel();
        nombre_text1 = new javax.swing.JLabel();
        productos = new javax.swing.JComboBox<>();
        correo_text1 = new javax.swing.JLabel();
        anio = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        cambios_text = new javax.swing.JLabel();
        registrarCompra = new javax.swing.JButton();
        nombre_text2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(JFramePrincipal.sistema.getCliente(index).toString());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productosComprados_text.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        productosComprados_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productosComprados_text.setText("Productos comprados");
        jPanel1.add(productosComprados_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 470, 22));

        nombreCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 11, 309, -1));

        guardarNombre.setBackground(new java.awt.Color(255, 255, 255));
        guardarNombre.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarNombre.setText("Guardar");
        guardarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(guardarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 11, -1, 22));

        apellido_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        apellido_text.setText("Apellido:");
        jPanel1.add(apellido_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, 22));

        apellidoCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(apellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 39, 309, -1));

        guardarApellido.setBackground(new java.awt.Color(255, 255, 255));
        guardarApellido.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarApellido.setText("Guardar");
        guardarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 39, -1, 22));

        ciCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(ciCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 67, 309, -1));

        guardarCi.setBackground(new java.awt.Color(255, 255, 255));
        guardarCi.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarCi.setText("Guardar");
        guardarCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCiActionPerformed(evt);
            }
        });
        jPanel1.add(guardarCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 67, -1, 22));

        ci_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        ci_text.setText("CI:");
        jPanel1.add(ci_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, -1, 22));

        guardarTelefono.setBackground(new java.awt.Color(255, 255, 255));
        guardarTelefono.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarTelefono.setText("Guardar");
        guardarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 95, -1, 22));

        telefono_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        telefono_text.setText("Telefono:");
        jPanel1.add(telefono_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, 22));

        telefonoCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        telefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(telefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 95, 309, -1));

        correo_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        correo_text.setText("Fecha");
        jPanel1.add(correo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, 20));

        guardarCorreo.setBackground(new java.awt.Color(255, 255, 255));
        guardarCorreo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarCorreo.setText("Guardar");
        guardarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 123, -1, 22));

        correoCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(correoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 123, 309, -1));

        registrarCompra_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        registrarCompra_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(registrarCompra_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 488, 30));

        nombre_text1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nombre_text1.setText("Nombre: ");
        jPanel1.add(nombre_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 22));

        productos.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosActionPerformed(evt);
            }
        });
        jPanel1.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 20));

        correo_text1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        correo_text1.setText("EMail:");
        jPanel1.add(correo_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, 22));

        anio.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        anio.setToolTipText("Anio");
        jPanel1.add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 60, 20));

        dia.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        dia.setToolTipText("Dia");
        jPanel1.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 40, 20));

        mes.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        mes.setToolTipText("Mes");
        jPanel1.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 40, 20));

        cambios_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cambios_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cambios_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 488, 33));

        registrarCompra.setBackground(new java.awt.Color(255, 255, 255));
        registrarCompra.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        registrarCompra.setText("Comprar");
        registrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCompraActionPerformed(evt);
            }
        });
        jPanel1.add(registrarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        nombre_text2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nombre_text2.setText("Compra de producto");
        jPanel1.add(nombre_text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 440, 22));

        jScrollPane1.setViewportView(listaProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 440, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoClienteActionPerformed

    private void guardarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarNombreActionPerformed
        if(nombreCliente.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El nombre no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getCliente(index).setNombre(nombreCliente.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Nombre cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarNombreActionPerformed

    private void guardarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarApellidoActionPerformed
        if(apellidoCliente.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El apellido no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getCliente(index).setApellido(apellidoCliente.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Apellido cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarApellidoActionPerformed

    private void guardarCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCiActionPerformed
        if(ciCliente.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("La cedula de identidad no puede estar en blanco.");
        } else if(JFramePrincipal.sistema.verificarCliente(ciCliente.getText())) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("Este cliente ya existe.");
        } else {
            JFramePrincipal.sistema.getCliente(index).setCi(ciCliente.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Cedula de identidad cambiada satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarCiActionPerformed

    private void guardarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTelefonoActionPerformed
        if(telefonoCliente.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El telefono no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getCliente(index).setTelefono(ciCliente.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Telefono cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarTelefonoActionPerformed

    private void guardarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCorreoActionPerformed
        if(correoCliente.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El correo electronico no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getCliente(index).setCorreo(correoCliente.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Correo electronico cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarCorreoActionPerformed

    private void registrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCompraActionPerformed
        if(productos.getSelectedIndex() > -1) {
            JFramePrincipal.sistema.addVenta(new Venta(dia.getText() + "/" + mes.getText() + "/" + anio.getText(),JFramePrincipal.sistema.getCliente(index),JFramePrincipal.sistema.getProducto(productos.getSelectedIndex())));
            JFramePrincipal.sistema.getCliente(index).addCompra(JFramePrincipal.sistema.getProducto(productos.getSelectedIndex()));
            registrarCompra_text.setForeground(Color.BLACK);
            registrarCompra_text.setText("Producto comprado satisfactoriamente.");
            actualizarListaProductos();
        }
    }//GEN-LAST:event_registrarCompraActionPerformed

    private void productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anio;
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JLabel apellido_text;
    private javax.swing.JLabel cambios_text;
    private javax.swing.JTextField ciCliente;
    private javax.swing.JLabel ci_text;
    private javax.swing.JTextField correoCliente;
    private javax.swing.JLabel correo_text;
    private javax.swing.JLabel correo_text1;
    private javax.swing.JTextField dia;
    private javax.swing.JButton guardarApellido;
    private javax.swing.JButton guardarCi;
    private javax.swing.JButton guardarCorreo;
    private javax.swing.JButton guardarNombre;
    private javax.swing.JButton guardarTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JLabel nombre_text1;
    private javax.swing.JLabel nombre_text2;
    private javax.swing.JComboBox<String> productos;
    private javax.swing.JLabel productosComprados_text;
    private javax.swing.JButton registrarCompra;
    private javax.swing.JLabel registrarCompra_text;
    private javax.swing.JTextField telefonoCliente;
    private javax.swing.JLabel telefono_text;
    // End of variables declaration//GEN-END:variables

    private void actualizarListaProductos() {
        listaProductos.setModel(JFramePrincipal.sistema.getCliente(index).getProductoModel());
    }
}
