/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designbosco;

import java.awt.Color;
import java.awt.Component;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.ListModel;

/**
 *
 * @author Ezequiel Melogno
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */

    
    static Sistema sistema = new Sistema();
    public JFramePrincipal() {
        initComponents();
        ImageIcon iconLogo = new ImageIcon("Images/logo.png");
        logo.setIcon(iconLogo);
        actualizarListaClientes();
        actualizarListaProductos();
        actualizarListaLocales();
        actualizarListaProyectos();
        actualizarTablaVentas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        designBoscoTab = new javax.swing.JTabbedPane();
        inicio = new javax.swing.JPanel();
        bienvenido_text = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        productos = new javax.swing.JPanel();
        listaProductosContainer = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        productos_text = new javax.swing.JLabel();
        anadirProducto = new javax.swing.JButton();
        eliminarProducto = new javax.swing.JButton();
        editarProducto = new javax.swing.JButton();
        nombreProducto = new javax.swing.JTextField();
        nombreProducto_text = new javax.swing.JLabel();
        anadirProducto_text = new javax.swing.JLabel();
        precioProducto_text = new javax.swing.JLabel();
        precioProducto = new javax.swing.JTextField();
        tipoProducto_text = new javax.swing.JLabel();
        descripcionProducto_text = new javax.swing.JLabel();
        verProducto = new javax.swing.JButton();
        actualizarListaProductos = new javax.swing.JButton();
        tipoProducto = new javax.swing.JComboBox<>();
        descripcionProductoContainer = new javax.swing.JScrollPane();
        descripcionProducto = new javax.swing.JTextArea();
        productoDarDeAlta = new javax.swing.JLabel();
        buscarProducto = new javax.swing.JButton();
        clientes = new javax.swing.JPanel();
        listaClientesContainer = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        clientes_text = new javax.swing.JLabel();
        anadirCliente = new javax.swing.JButton();
        eliminarCliente = new javax.swing.JButton();
        editarCliente = new javax.swing.JButton();
        nombreCliente = new javax.swing.JTextField();
        nombreCliente_text = new javax.swing.JLabel();
        anadirCliente_text = new javax.swing.JLabel();
        apellidoCliente_text = new javax.swing.JLabel();
        apellidoCliente = new javax.swing.JTextField();
        ciCliente = new javax.swing.JTextField();
        ciCliente_text = new javax.swing.JLabel();
        telefonoCliente_text = new javax.swing.JLabel();
        telefonoCliente = new javax.swing.JTextField();
        correoCliente = new javax.swing.JTextField();
        correoCliente_text = new javax.swing.JLabel();
        clienteDarDeAlta = new javax.swing.JLabel();
        verCliente = new javax.swing.JButton();
        actualizarListaClientes = new javax.swing.JButton();
        buscarCliente = new javax.swing.JButton();
        locales = new javax.swing.JPanel();
        listaClientesContainer1 = new javax.swing.JScrollPane();
        listaLocales = new javax.swing.JList<>();
        locales_text = new javax.swing.JLabel();
        anadirLocal = new javax.swing.JButton();
        eliminarLocal = new javax.swing.JButton();
        editarLocal = new javax.swing.JButton();
        departamentoLocal_text = new javax.swing.JLabel();
        anadirLocal_text = new javax.swing.JLabel();
        ciudadLocal_text = new javax.swing.JLabel();
        ciudadLocal = new javax.swing.JTextField();
        direccionLocal = new javax.swing.JTextField();
        direccionLocal_text = new javax.swing.JLabel();
        localDarDeAlta = new javax.swing.JLabel();
        verLocal = new javax.swing.JButton();
        actualizarListaLocales = new javax.swing.JButton();
        departamentoLocal = new javax.swing.JComboBox<>();
        buscarLocal = new javax.swing.JButton();
        proyectos = new javax.swing.JPanel();
        listaProductosContainer1 = new javax.swing.JScrollPane();
        listaProyectos = new javax.swing.JList<>();
        proyectos_text = new javax.swing.JLabel();
        anadirProyecto = new javax.swing.JButton();
        eliminarProyecto = new javax.swing.JButton();
        editarProyecto = new javax.swing.JButton();
        nombreProyecto = new javax.swing.JTextField();
        nombreProyecto_text = new javax.swing.JLabel();
        anadirProducto_text1 = new javax.swing.JLabel();
        descripcionProyecto_text = new javax.swing.JLabel();
        verProyecto = new javax.swing.JButton();
        actualizarListaProyectos = new javax.swing.JButton();
        descripcionProductoContainer1 = new javax.swing.JScrollPane();
        descripcionProyecto = new javax.swing.JTextArea();
        proyectoDarDeAlta = new javax.swing.JLabel();
        buscarProyecto = new javax.swing.JButton();
        ventas = new javax.swing.JPanel();
        ventas_text = new javax.swing.JLabel();
        eliminarVenta = new javax.swing.JButton();
        actualizarTablaVentas = new javax.swing.JButton();
        tablaVentasContainer = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor DesignBosco");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        designBoscoTab.setBackground(new java.awt.Color(255, 255, 255));
        designBoscoTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        designBoscoTab.setToolTipText("");
        designBoscoTab.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        designBoscoTab.setPreferredSize(new java.awt.Dimension(800, 500));

        inicio.setBackground(new java.awt.Color(255, 255, 255));
        inicio.setPreferredSize(new java.awt.Dimension(800, 600));
        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenido_text.setBackground(new java.awt.Color(255, 255, 255));
        bienvenido_text.setFont(new java.awt.Font("Ubuntu Medium", 0, 28)); // NOI18N
        bienvenido_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido_text.setText("ienvenido al Gestor ABMC de DesignBosco");
        inicio.add(bienvenido_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 580, 400));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 70));

        designBoscoTab.addTab("Inicio", inicio);

        productos.setBackground(new java.awt.Color(255, 255, 255));
        productos.setPreferredSize(new java.awt.Dimension(800, 600));
        productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaProductosContainer.setViewportView(listaProductos);

        productos.add(listaProductosContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 56, 240, 480));

        productos_text.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        productos_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos_text.setText("Productos");
        productos.add(productos_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 11, 240, 34));

        anadirProducto.setBackground(new java.awt.Color(255, 255, 255));
        anadirProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        anadirProducto.setText("Anadir");
        anadirProducto.setActionCommand("");
        anadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirProductoActionPerformed(evt);
            }
        });
        productos.add(anadirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 364, 224, -1));

        eliminarProducto.setBackground(new java.awt.Color(255, 255, 255));
        eliminarProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        eliminarProducto.setText("Eliminar");
        eliminarProducto.setActionCommand("");
        eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductoActionPerformed(evt);
            }
        });
        productos.add(eliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        editarProducto.setBackground(new java.awt.Color(255, 255, 255));
        editarProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        editarProducto.setText("Editar");
        editarProducto.setActionCommand("");
        editarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProductoActionPerformed(evt);
            }
        });
        productos.add(editarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 85, -1));
        productos.add(nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 224, -1));

        nombreProducto_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        nombreProducto_text.setText("Nombre");
        productos.add(nombreProducto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        anadirProducto_text.setBackground(new java.awt.Color(255, 255, 255));
        anadirProducto_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        anadirProducto_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirProducto_text.setText("Anadir Producto");
        productos.add(anadirProducto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 56, -1, -1));

        precioProducto_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        precioProducto_text.setText("Precio (En pesos uruguayos)");
        productos.add(precioProducto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, -1, -1));
        productos.add(precioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 224, -1));

        tipoProducto_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        tipoProducto_text.setText("Tipo");
        productos.add(tipoProducto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, -1, -1));

        descripcionProducto_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        descripcionProducto_text.setText("Descripcion");
        productos.add(descripcionProducto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, -1, -1));

        verProducto.setBackground(new java.awt.Color(255, 255, 255));
        verProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        verProducto.setText("Ver");
        verProducto.setActionCommand("");
        verProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProductoActionPerformed(evt);
            }
        });
        productos.add(verProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 85, -1));

        actualizarListaProductos.setBackground(new java.awt.Color(255, 255, 255));
        actualizarListaProductos.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        actualizarListaProductos.setText("Actualizar");
        actualizarListaProductos.setActionCommand("");
        actualizarListaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarListaProductosActionPerformed(evt);
            }
        });
        productos.add(actualizarListaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        tipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Elige un tipo de proyecto*", "Diseno pagina web", "Desarrollo de aplicacion", "Otro" }));
        productos.add(tipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, 224, -1));

        descripcionProducto.setColumns(20);
        descripcionProducto.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        descripcionProducto.setRows(5);
        descripcionProductoContainer.setViewportView(descripcionProducto);

        productos.add(descripcionProductoContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 263, 224, 90));

        productoDarDeAlta.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        productoDarDeAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productos.add(productoDarDeAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 224, 78));

        buscarProducto.setBackground(new java.awt.Color(255, 255, 255));
        buscarProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        buscarProducto.setText("Buscar");
        buscarProducto.setActionCommand("");
        buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductoActionPerformed(evt);
            }
        });
        productos.add(buscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 85, -1));

        designBoscoTab.addTab("Productos", productos);

        clientes.setBackground(new java.awt.Color(255, 255, 255));
        clientes.setPreferredSize(new java.awt.Dimension(800, 600));
        clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaClientesContainer.setViewportView(listaClientes);

        clientes.add(listaClientesContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 56, 240, 480));

        clientes_text.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        clientes_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientes_text.setText("Clientes");
        clientes.add(clientes_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 11, 240, 34));

        anadirCliente.setBackground(new java.awt.Color(255, 255, 255));
        anadirCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        anadirCliente.setText("Anadir");
        anadirCliente.setActionCommand("");
        anadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirClienteActionPerformed(evt);
            }
        });
        clientes.add(anadirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 371, 224, -1));

        eliminarCliente.setBackground(new java.awt.Color(255, 255, 255));
        eliminarCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        eliminarCliente.setText("Eliminar");
        eliminarCliente.setActionCommand("");
        eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClienteActionPerformed(evt);
            }
        });
        clientes.add(eliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        editarCliente.setBackground(new java.awt.Color(255, 255, 255));
        editarCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        editarCliente.setText("Editar");
        editarCliente.setActionCommand("");
        editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteActionPerformed(evt);
            }
        });
        clientes.add(editarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 85, -1));
        clientes.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 224, -1));

        nombreCliente_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        nombreCliente_text.setText("Nombre");
        clientes.add(nombreCliente_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        anadirCliente_text.setBackground(new java.awt.Color(255, 255, 255));
        anadirCliente_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        anadirCliente_text.setText("Anadir Cliente");
        clientes.add(anadirCliente_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 56, -1, -1));

        apellidoCliente_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        apellidoCliente_text.setText("Apellido");
        clientes.add(apellidoCliente_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, -1, -1));
        clientes.add(apellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 224, -1));
        clientes.add(ciCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, 224, -1));

        ciCliente_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        ciCliente_text.setText("Cedula de identidad");
        clientes.add(ciCliente_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, -1, -1));

        telefonoCliente_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        telefonoCliente_text.setText("Telefono");
        clientes.add(telefonoCliente_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 248, -1, -1));
        clientes.add(telefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, 224, -1));
        clientes.add(correoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 319, 224, -1));

        correoCliente_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        correoCliente_text.setText("Correo electronico");
        clientes.add(correoCliente_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, -1, -1));

        clienteDarDeAlta.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        clienteDarDeAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientes.add(clienteDarDeAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 414, 224, 89));

        verCliente.setBackground(new java.awt.Color(255, 255, 255));
        verCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        verCliente.setText("Ver");
        verCliente.setActionCommand("");
        verCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClienteActionPerformed(evt);
            }
        });
        clientes.add(verCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 85, -1));

        actualizarListaClientes.setBackground(new java.awt.Color(255, 255, 255));
        actualizarListaClientes.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        actualizarListaClientes.setText("Actualizar");
        actualizarListaClientes.setActionCommand("");
        actualizarListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarListaClientesActionPerformed(evt);
            }
        });
        clientes.add(actualizarListaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        buscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        buscarCliente.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        buscarCliente.setText("Buscar");
        buscarCliente.setActionCommand("");
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });
        clientes.add(buscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 85, -1));

        designBoscoTab.addTab("Clientes", clientes);

        locales.setBackground(new java.awt.Color(255, 255, 255));
        locales.setPreferredSize(new java.awt.Dimension(800, 600));
        locales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaClientesContainer1.setViewportView(listaLocales);

        locales.add(listaClientesContainer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 56, 300, 480));

        locales_text.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        locales_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        locales_text.setText("Locales");
        locales.add(locales_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 11, 300, 34));

        anadirLocal.setBackground(new java.awt.Color(255, 255, 255));
        anadirLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        anadirLocal.setText("Anadir");
        anadirLocal.setActionCommand("");
        anadirLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirLocalActionPerformed(evt);
            }
        });
        locales.add(anadirLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, -1));

        eliminarLocal.setBackground(new java.awt.Color(255, 255, 255));
        eliminarLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        eliminarLocal.setText("Eliminar");
        eliminarLocal.setActionCommand("");
        eliminarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLocalActionPerformed(evt);
            }
        });
        locales.add(eliminarLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        editarLocal.setBackground(new java.awt.Color(255, 255, 255));
        editarLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        editarLocal.setText("Editar");
        editarLocal.setActionCommand("");
        editarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarLocalActionPerformed(evt);
            }
        });
        locales.add(editarLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 85, -1));

        departamentoLocal_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        departamentoLocal_text.setText("Departamento");
        locales.add(departamentoLocal_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        anadirLocal_text.setBackground(new java.awt.Color(255, 255, 255));
        anadirLocal_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        anadirLocal_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirLocal_text.setText("Anadir Local");
        locales.add(anadirLocal_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 30));

        ciudadLocal_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        ciudadLocal_text.setText("Ciudad");
        locales.add(ciudadLocal_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        locales.add(ciudadLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, -1));
        locales.add(direccionLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, -1));

        direccionLocal_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        direccionLocal_text.setText("Direccion");
        locales.add(direccionLocal_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        localDarDeAlta.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        localDarDeAlta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        locales.add(localDarDeAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 220, 89));

        verLocal.setBackground(new java.awt.Color(255, 255, 255));
        verLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        verLocal.setText("Ver");
        verLocal.setActionCommand("");
        verLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verLocalActionPerformed(evt);
            }
        });
        locales.add(verLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 85, -1));

        actualizarListaLocales.setBackground(new java.awt.Color(255, 255, 255));
        actualizarListaLocales.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        actualizarListaLocales.setText("Actualizar");
        actualizarListaLocales.setActionCommand("");
        actualizarListaLocales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarListaLocalesActionPerformed(evt);
            }
        });
        locales.add(actualizarListaLocales, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        departamentoLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Elige un departamento*", "Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", "Flores", "Florida", "Lavalleja", "Maldonado", "Montevideo", "Paysandu", "Rio Negro", "Rivera", "Rocha", "Salto", "San Jose", "Soriano", "Tacuarembo", "Treinta y Tres" }));
        locales.add(departamentoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, -1));

        buscarLocal.setBackground(new java.awt.Color(255, 255, 255));
        buscarLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        buscarLocal.setText("Buscar");
        buscarLocal.setActionCommand("");
        buscarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLocalActionPerformed(evt);
            }
        });
        locales.add(buscarLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 85, -1));

        designBoscoTab.addTab("Locales", locales);

        proyectos.setBackground(new java.awt.Color(255, 255, 255));
        proyectos.setPreferredSize(new java.awt.Dimension(800, 600));
        proyectos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaProductosContainer1.setViewportView(listaProyectos);

        proyectos.add(listaProductosContainer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 56, 240, 480));

        proyectos_text.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        proyectos_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proyectos_text.setText("Proyectos");
        proyectos.add(proyectos_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 11, 240, 34));

        anadirProyecto.setBackground(new java.awt.Color(255, 255, 255));
        anadirProyecto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        anadirProyecto.setText("Anadir");
        anadirProyecto.setActionCommand("");
        anadirProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirProyectoActionPerformed(evt);
            }
        });
        proyectos.add(anadirProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 224, -1));

        eliminarProyecto.setBackground(new java.awt.Color(255, 255, 255));
        eliminarProyecto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        eliminarProyecto.setText("Eliminar");
        eliminarProyecto.setActionCommand("");
        eliminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProyectoActionPerformed(evt);
            }
        });
        proyectos.add(eliminarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        editarProyecto.setBackground(new java.awt.Color(255, 255, 255));
        editarProyecto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        editarProyecto.setText("Editar");
        editarProyecto.setActionCommand("");
        editarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProyectoActionPerformed(evt);
            }
        });
        proyectos.add(editarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 85, -1));
        proyectos.add(nombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, 224, -1));

        nombreProyecto_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        nombreProyecto_text.setText("Nombre");
        proyectos.add(nombreProyecto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        anadirProducto_text1.setBackground(new java.awt.Color(255, 255, 255));
        anadirProducto_text1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        anadirProducto_text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anadirProducto_text1.setText("Anadir Proyecto");
        proyectos.add(anadirProducto_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, 220, -1));

        descripcionProyecto_text.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        descripcionProyecto_text.setText("Descripcion");
        proyectos.add(descripcionProyecto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        verProyecto.setBackground(new java.awt.Color(255, 255, 255));
        verProyecto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        verProyecto.setText("Ver");
        verProyecto.setActionCommand("");
        verProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProyectoActionPerformed(evt);
            }
        });
        proyectos.add(verProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 85, -1));

        actualizarListaProyectos.setBackground(new java.awt.Color(255, 255, 255));
        actualizarListaProyectos.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        actualizarListaProyectos.setText("Actualizar");
        actualizarListaProyectos.setActionCommand("");
        actualizarListaProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarListaProyectosActionPerformed(evt);
            }
        });
        proyectos.add(actualizarListaProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        descripcionProyecto.setColumns(20);
        descripcionProyecto.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        descripcionProyecto.setRows(5);
        descripcionProductoContainer1.setViewportView(descripcionProyecto);

        proyectos.add(descripcionProductoContainer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 224, 190));

        proyectoDarDeAlta.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        proyectoDarDeAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proyectos.add(proyectoDarDeAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 224, 78));

        buscarProyecto.setBackground(new java.awt.Color(255, 255, 255));
        buscarProyecto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        buscarProyecto.setText("Buscar");
        buscarProyecto.setActionCommand("");
        buscarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProyectoActionPerformed(evt);
            }
        });
        proyectos.add(buscarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 85, -1));

        designBoscoTab.addTab("Proyectos", proyectos);

        ventas.setBackground(new java.awt.Color(255, 255, 255));
        ventas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ventas_text.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        ventas_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventas_text.setText("Ventas");
        ventas.add(ventas_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 630, 40));

        eliminarVenta.setBackground(new java.awt.Color(255, 255, 255));
        eliminarVenta.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        eliminarVenta.setText("Eliminar");
        eliminarVenta.setActionCommand("");
        eliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVentaActionPerformed(evt);
            }
        });
        ventas.add(eliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 120, -1));

        actualizarTablaVentas.setBackground(new java.awt.Color(255, 255, 255));
        actualizarTablaVentas.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        actualizarTablaVentas.setText("Actualizar");
        actualizarTablaVentas.setActionCommand("");
        actualizarTablaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTablaVentasActionPerformed(evt);
            }
        });
        ventas.add(actualizarTablaVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 120, -1));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Fecha", "Producto", "$$$"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentasContainer.setViewportView(tablaVentas);

        ventas.add(tablaVentasContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 620, 410));

        designBoscoTab.addTab("Ventas", ventas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(designBoscoTab, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(designBoscoTab, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("Programa gestor ABMC de la empresa DesignBosco.");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void anadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirClienteActionPerformed
        if(nombreCliente.getText().isBlank() || 
           apellidoCliente.getText().isBlank() || 
           telefonoCliente.getText().isBlank() || 
           ciCliente.getText().isBlank() ||
           correoCliente.getText().isBlank() ) {
           clienteDarDeAlta.setForeground(Color.RED);
           clienteDarDeAlta.setText("Faltan campos para rellenar.");
        } else if (sistema.verificarCliente(ciCliente.getText())) {
           clienteDarDeAlta.setForeground(Color.RED);
           clienteDarDeAlta.setText("Este cliente ya existe.");
        } else {       
            sistema.addCliente(new Cliente(nombreCliente.getText(),apellidoCliente.getText(),ciCliente.getText(),correoCliente.getText(),telefonoCliente.getText()));
            actualizarListaClientes();
            clienteDarDeAlta.setForeground(Color.BLACK);
            clienteDarDeAlta.setText("Cliente anadido con exito.");
        }
    }//GEN-LAST:event_anadirClienteActionPerformed

    private void eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteActionPerformed
        if(listaClientes.getSelectedIndex() > -1) {
            sistema.removeCliente(listaClientes.getSelectedIndex());
            actualizarListaClientes();
        }
    }//GEN-LAST:event_eliminarClienteActionPerformed

    public void actualizarListaClientes() {
        listaClientes.setModel(sistema.getClienteModel());
    }
    
    private void editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteActionPerformed
        if(listaClientes.getSelectedIndex() > -1) {
            new JFrameCliente(listaClientes.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_editarClienteActionPerformed

    private void actualizarListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarListaClientesActionPerformed
        actualizarListaClientes();
    }//GEN-LAST:event_actualizarListaClientesActionPerformed

    private void verClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClienteActionPerformed
        if(listaClientes.getSelectedIndex() > -1) {
            new JFrameCliente(listaClientes.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_verClienteActionPerformed

    private void actualizarListaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarListaProductosActionPerformed
        actualizarListaProductos();
    }//GEN-LAST:event_actualizarListaProductosActionPerformed

    private void verProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProductoActionPerformed
        if(listaProductos.getSelectedIndex() > -1) {
            new JFrameProducto(listaProductos.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_verProductoActionPerformed

    private void editarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProductoActionPerformed
        if(listaProductos.getSelectedIndex() > -1) {
            new JFrameProducto(listaProductos.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_editarProductoActionPerformed

    private void eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoActionPerformed
        if(listaProductos.getSelectedIndex() > -1) {
            sistema.removeProducto(listaProductos.getSelectedIndex());
            actualizarListaProductos();
        }
    }//GEN-LAST:event_eliminarProductoActionPerformed

    public static boolean chequearSiEsEntero(String mystr) {
        try {
            int i = Integer.valueOf(mystr);
        } catch (NumberFormatException | NullPointerException nfe) {
            return false;
        }
        return true;
    }
    
//    public ComboBoxModel<String> getTipoProducto() {
//        return tipoProducto.getModel();
//    }
    
    public void actualizarListaProductos() {
        listaProductos.setModel(sistema.getProductoModel());
    }
    
    private void anadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirProductoActionPerformed
        if(nombreProducto.getText().isBlank() ||
            precioProducto.getText().isBlank() ||
            descripcionProducto.getText().isBlank() ) {
            productoDarDeAlta.setForeground(Color.RED);
            productoDarDeAlta.setText("Faltan campos para rellenar.");
        } else if (sistema.verificarProducto(nombreProducto.getText())) {
            productoDarDeAlta.setForeground(Color.RED);
            productoDarDeAlta.setText("Este producto ya existe.");
        } else if (tipoProducto.getSelectedIndex() == 0) {
            productoDarDeAlta.setForeground(Color.RED);
            productoDarDeAlta.setText("El producto tiene que tener un tipo.");
        } else if (!chequearSiEsEntero(precioProducto.getText())) {
            productoDarDeAlta.setForeground(Color.RED);
            productoDarDeAlta.setText("El precio del producto tiene que ser un entero.");
        } else {
            sistema.addProducto(new Producto(nombreProducto.getText(), Integer.valueOf(precioProducto.getText()), tipoProducto.getSelectedIndex(), descripcionProducto.getText()));
            actualizarListaProductos();
            productoDarDeAlta.setForeground(Color.BLACK);
            productoDarDeAlta.setText("Producto anadido con exito.");
        }
    }//GEN-LAST:event_anadirProductoActionPerformed

        public void actualizarListaLocales() {
            listaLocales.setModel(sistema.getLocalModel());
        }
    
    private void anadirLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirLocalActionPerformed
        if(ciudadLocal.getText().isBlank() ||
        direccionLocal.getText().isBlank() ) {
            localDarDeAlta.setForeground(Color.RED);
            localDarDeAlta.setText("Faltan campos para rellenar.");
        } else if (departamentoLocal.getSelectedIndex() == 0) {
            localDarDeAlta.setForeground(Color.RED);
            localDarDeAlta.setText("Falta elegir departamento.");
        } else {
            sistema.addLocal(new Local(departamentoLocal.getSelectedIndex(), ciudadLocal.getText(), direccionLocal.getText()));
            actualizarListaLocales();
            localDarDeAlta.setForeground(Color.BLACK);
            localDarDeAlta.setText("Local anadido con exito.");
        }
    }//GEN-LAST:event_anadirLocalActionPerformed

    private void eliminarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLocalActionPerformed
        if(listaLocales.getSelectedIndex() > -1) {
            sistema.removeLocal(listaLocales.getSelectedIndex());
            actualizarListaLocales();
        }
    }//GEN-LAST:event_eliminarLocalActionPerformed

    private void editarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarLocalActionPerformed
        if(listaLocales.getSelectedIndex() > -1) {
            new JFrameLocal(listaLocales.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_editarLocalActionPerformed

    private void verLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verLocalActionPerformed
        if(listaLocales.getSelectedIndex() > -1) {
            new JFrameLocal(listaLocales.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_verLocalActionPerformed

    private void actualizarListaLocalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarListaLocalesActionPerformed
        actualizarListaLocales();
    }//GEN-LAST:event_actualizarListaLocalesActionPerformed

    private void actualizarListaProyectos() {
        listaProyectos.setModel(sistema.getProyectoModel());
    }
    
    private void anadirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirProyectoActionPerformed
        if(nombreProyecto.getText().isBlank() ||
        descripcionProyecto.getText().isBlank() ) {
            proyectoDarDeAlta.setForeground(Color.RED);
            proyectoDarDeAlta.setText("Faltan campos para rellenar.");
        } else if (sistema.verificarProyecto(nombreProyecto.getText())) {
            proyectoDarDeAlta.setForeground(Color.RED);
            proyectoDarDeAlta.setText("Este proyecto ya existe.");
        } else {
            sistema.addProyecto(new Proyecto(nombreProyecto.getText(), descripcionProyecto.getText()));
            actualizarListaProyectos();
            proyectoDarDeAlta.setForeground(Color.BLACK);
            proyectoDarDeAlta.setText("Proyecto anadido con exito.");
        }
    }//GEN-LAST:event_anadirProyectoActionPerformed

    private void eliminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProyectoActionPerformed
        if(listaProyectos.getSelectedIndex() > -1) {
            sistema.removeProyecto(listaProyectos.getSelectedIndex());
            actualizarListaProyectos();
        }
    }//GEN-LAST:event_eliminarProyectoActionPerformed

    private void editarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProyectoActionPerformed
        if(listaProyectos.getSelectedIndex() > -1) {
            new JFrameProyecto(listaProyectos.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_editarProyectoActionPerformed

    private void verProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProyectoActionPerformed
        if(listaProyectos.getSelectedIndex() > -1) {
            new JFrameProyecto(listaProyectos.getSelectedIndex()).setVisible(true);
        }
    }//GEN-LAST:event_verProyectoActionPerformed

    private void actualizarListaProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarListaProyectosActionPerformed
        actualizarListaProyectos();
    }//GEN-LAST:event_actualizarListaProyectosActionPerformed

    private void actualizarTablaVentas() {
        tablaVentas.setModel(sistema.getVentaModel());
    }
    
    private void eliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVentaActionPerformed
        if(tablaVentas.getSelectedRow() > -1) {
            sistema.removeVenta(tablaVentas.getSelectedRow());
        }
        
    }//GEN-LAST:event_eliminarVentaActionPerformed

    private void actualizarTablaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTablaVentasActionPerformed
        actualizarTablaVentas();
    }//GEN-LAST:event_actualizarTablaVentasActionPerformed

    private void buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoActionPerformed
        new JFrameBuscarProducto().setVisible(true);
    }//GEN-LAST:event_buscarProductoActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        new JFrameBuscarCliente().setVisible(true);
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void buscarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLocalActionPerformed
        new JFrameBuscarLocal().setVisible(true);
    }//GEN-LAST:event_buscarLocalActionPerformed

    private void buscarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProyectoActionPerformed
        new JFrameBuscarProyecto().setVisible(true);
    }//GEN-LAST:event_buscarProyectoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarListaClientes;
    private javax.swing.JButton actualizarListaLocales;
    private javax.swing.JButton actualizarListaProductos;
    private javax.swing.JButton actualizarListaProyectos;
    private javax.swing.JButton actualizarTablaVentas;
    private javax.swing.JButton anadirCliente;
    private javax.swing.JLabel anadirCliente_text;
    private javax.swing.JButton anadirLocal;
    private javax.swing.JLabel anadirLocal_text;
    private javax.swing.JButton anadirProducto;
    private javax.swing.JLabel anadirProducto_text;
    private javax.swing.JLabel anadirProducto_text1;
    private javax.swing.JButton anadirProyecto;
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JLabel apellidoCliente_text;
    private javax.swing.JLabel bienvenido_text;
    private javax.swing.JButton buscarCliente;
    private javax.swing.JButton buscarLocal;
    private javax.swing.JButton buscarProducto;
    private javax.swing.JButton buscarProyecto;
    private javax.swing.JTextField ciCliente;
    private javax.swing.JLabel ciCliente_text;
    private javax.swing.JTextField ciudadLocal;
    private javax.swing.JLabel ciudadLocal_text;
    private javax.swing.JLabel clienteDarDeAlta;
    private javax.swing.JPanel clientes;
    private javax.swing.JLabel clientes_text;
    private javax.swing.JTextField correoCliente;
    private javax.swing.JLabel correoCliente_text;
    private javax.swing.JComboBox<String> departamentoLocal;
    private javax.swing.JLabel departamentoLocal_text;
    private javax.swing.JTextArea descripcionProducto;
    private javax.swing.JScrollPane descripcionProductoContainer;
    private javax.swing.JScrollPane descripcionProductoContainer1;
    private javax.swing.JLabel descripcionProducto_text;
    private javax.swing.JTextArea descripcionProyecto;
    private javax.swing.JLabel descripcionProyecto_text;
    private javax.swing.JTabbedPane designBoscoTab;
    private javax.swing.JTextField direccionLocal;
    private javax.swing.JLabel direccionLocal_text;
    private javax.swing.JButton editarCliente;
    private javax.swing.JButton editarLocal;
    private javax.swing.JButton editarProducto;
    private javax.swing.JButton editarProyecto;
    private javax.swing.JButton eliminarCliente;
    private javax.swing.JButton eliminarLocal;
    private javax.swing.JButton eliminarProducto;
    private javax.swing.JButton eliminarProyecto;
    private javax.swing.JButton eliminarVenta;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel inicio;
    private javax.swing.JList<String> listaClientes;
    private javax.swing.JScrollPane listaClientesContainer;
    private javax.swing.JScrollPane listaClientesContainer1;
    private javax.swing.JList<String> listaLocales;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JScrollPane listaProductosContainer;
    private javax.swing.JScrollPane listaProductosContainer1;
    private javax.swing.JList<String> listaProyectos;
    private javax.swing.JLabel localDarDeAlta;
    private javax.swing.JPanel locales;
    private javax.swing.JLabel locales_text;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JLabel nombreCliente_text;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JLabel nombreProducto_text;
    private javax.swing.JTextField nombreProyecto;
    private javax.swing.JLabel nombreProyecto_text;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JLabel precioProducto_text;
    private javax.swing.JLabel productoDarDeAlta;
    private javax.swing.JPanel productos;
    private javax.swing.JLabel productos_text;
    private javax.swing.JLabel proyectoDarDeAlta;
    private javax.swing.JPanel proyectos;
    private javax.swing.JLabel proyectos_text;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JScrollPane tablaVentasContainer;
    private javax.swing.JTextField telefonoCliente;
    private javax.swing.JLabel telefonoCliente_text;
    private javax.swing.JComboBox<String> tipoProducto;
    private javax.swing.JLabel tipoProducto_text;
    private javax.swing.JPanel ventas;
    private javax.swing.JLabel ventas_text;
    private javax.swing.JButton verCliente;
    private javax.swing.JButton verLocal;
    private javax.swing.JButton verProducto;
    private javax.swing.JButton verProyecto;
    // End of variables declaration//GEN-END:variables

    
}
