/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designbosco;

import java.awt.Color;

/**
 *
 * @author Ezequiel Melogno
 */
public class JFrameProyecto extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCliente
     */
    
    static int index;
    
    public JFrameProyecto(int index) {
        initComponents();
        this.index = index;
        nombreProyecto.setText(JFramePrincipal.sistema.getProyecto(index).getNombre());
        descripcionProyecto.setText(JFramePrincipal.sistema.getProyecto(index).getDescripcion());
        if(JFramePrincipal.sistema.getProyecto(index).getEstado().equals("Sin terminar")) {
            estado0Proyecto.setSelected(true);
        } else if (JFramePrincipal.sistema.getProyecto(index).getEstado().equals("Terminado")) {
            estado1Proyecto.setSelected(true);
        }
        actualizarListaEmpleadosAsignados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estadoProyecto = new javax.swing.ButtonGroup();
        empleados = new javax.swing.JTabbedPane();
        proyecto = new javax.swing.JPanel();
        nombreProyecto_text = new javax.swing.JLabel();
        nombreProyecto = new javax.swing.JTextField();
        guardarNombreProyecto = new javax.swing.JButton();
        estadoProyecto_text = new javax.swing.JLabel();
        guardarDescripcionProyecto = new javax.swing.JButton();
        descripcionProyecto_text = new javax.swing.JLabel();
        estado1Proyecto = new javax.swing.JRadioButton();
        estado0Proyecto = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionProyecto = new javax.swing.JTextArea();
        cambiosProyecto = new javax.swing.JLabel();
        Empleados = new javax.swing.JPanel();
        verEmpleado = new javax.swing.JButton();
        empleadosAsignados_text = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEmpleadosAsignados = new javax.swing.JList<>();
        actualizarListaEmpleados = new javax.swing.JButton();
        eliminarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(JFramePrincipal.sistema.getProyecto(index).toString());
        setResizable(false);

        empleados.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        empleados.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        proyecto.setBackground(new java.awt.Color(255, 255, 255));
        proyecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreProyecto_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nombreProyecto_text.setText("Nombre:");
        proyecto.add(nombreProyecto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));

        nombreProyecto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        proyecto.add(nombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 290, 20));

        guardarNombreProyecto.setBackground(new java.awt.Color(255, 255, 255));
        guardarNombreProyecto.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarNombreProyecto.setText("Guardar");
        guardarNombreProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarNombreProyectoActionPerformed(evt);
            }
        });
        proyecto.add(guardarNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 80, -1));

        estadoProyecto_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        estadoProyecto_text.setText("Estado:");
        proyecto.add(estadoProyecto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 20));

        guardarDescripcionProyecto.setBackground(new java.awt.Color(255, 255, 255));
        guardarDescripcionProyecto.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarDescripcionProyecto.setText("Guardar");
        guardarDescripcionProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDescripcionProyectoActionPerformed(evt);
            }
        });
        proyecto.add(guardarDescripcionProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 80, -1));

        descripcionProyecto_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        descripcionProyecto_text.setText("Descripcion:");
        proyecto.add(descripcionProyecto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 20));

        estado1Proyecto.setBackground(new java.awt.Color(255, 255, 255));
        estadoProyecto.add(estado1Proyecto);
        estado1Proyecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estado1Proyecto.setText("Terminado");
        estado1Proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado1ProyectoActionPerformed(evt);
            }
        });
        proyecto.add(estado1Proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 110, -1));

        estado0Proyecto.setBackground(new java.awt.Color(255, 255, 255));
        estadoProyecto.add(estado0Proyecto);
        estado0Proyecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estado0Proyecto.setText("Sin Terminar");
        estado0Proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado0ProyectoActionPerformed(evt);
            }
        });
        proyecto.add(estado0Proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 110, -1));

        descripcionProyecto.setColumns(20);
        descripcionProyecto.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        descripcionProyecto.setRows(5);
        jScrollPane1.setViewportView(descripcionProyecto);

        proyecto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 270, 240));

        cambiosProyecto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cambiosProyecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proyecto.add(cambiosProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 460, 70));

        empleados.addTab("Proyecto", proyecto);

        Empleados.setBackground(new java.awt.Color(255, 255, 255));
        Empleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        verEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        verEmpleado.setText("Ver");
        verEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEmpleadoActionPerformed(evt);
            }
        });
        Empleados.add(verEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 80, -1));

        empleadosAsignados_text.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        empleadosAsignados_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empleadosAsignados_text.setText("Empleados asignados al Proyecto");
        Empleados.add(empleadosAsignados_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 30));

        jScrollPane2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        listaEmpleadosAsignados.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(listaEmpleadosAsignados);

        Empleados.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 450, 350));

        actualizarListaEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        actualizarListaEmpleados.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        actualizarListaEmpleados.setText("Actualizar");
        actualizarListaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarListaEmpleadosActionPerformed(evt);
            }
        });
        Empleados.add(actualizarListaEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 100, -1));

        eliminarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        eliminarEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        eliminarEmpleado.setText("Eliminar");
        eliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpleadoActionPerformed(evt);
            }
        });
        Empleados.add(eliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 80, -1));

        empleados.addTab("Empleados", Empleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empleados, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empleados, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void estado1ProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado1ProyectoActionPerformed
        JFramePrincipal.sistema.getProyecto(index).setEstado(1);
    }//GEN-LAST:event_estado1ProyectoActionPerformed

    private void estado0ProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado0ProyectoActionPerformed
        JFramePrincipal.sistema.getProyecto(index).setEstado(0);
    }//GEN-LAST:event_estado0ProyectoActionPerformed

    private void guardarNombreProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarNombreProyectoActionPerformed
        if(nombreProyecto.getText().isBlank()) {
            cambiosProyecto.setForeground(Color.RED);
            cambiosProyecto.setText("El nombre no puede estar en blanco.");
        } else if (JFramePrincipal.sistema.verificarProyecto(nombreProyecto.getText())) {
            cambiosProyecto.setForeground(Color.RED);
            cambiosProyecto.setText("Este proyecto ya existe.");
        } else {
            JFramePrincipal.sistema.getProyecto(index).setNombre(nombreProyecto.getText());
            cambiosProyecto.setForeground(Color.BLACK);
            cambiosProyecto.setText("Nombre cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarNombreProyectoActionPerformed

    private void guardarDescripcionProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDescripcionProyectoActionPerformed
        if(descripcionProyecto.getText().isBlank()) {
            cambiosProyecto.setForeground(Color.RED);
            cambiosProyecto.setText("La descripcion no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getProyecto(index).setDescripcion(descripcionProyecto.getText());
            cambiosProyecto.setForeground(Color.BLACK);
            cambiosProyecto.setText("Descripcion cambiada satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarDescripcionProyectoActionPerformed

    private void verEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEmpleadoActionPerformed
        if(listaEmpleadosAsignados.getSelectedIndex() > -1) {
            new JFrameEmpleado(JFramePrincipal.sistema.getEmpleadoLocal(JFramePrincipal.sistema.getProyecto(index).getEmpleado(listaEmpleadosAsignados.getSelectedIndex())), JFramePrincipal.sistema.getEmpleadoIndex(JFramePrincipal.sistema.getProyecto(index).getEmpleado(listaEmpleadosAsignados.getSelectedIndex()))).setVisible(true);
        }
    }//GEN-LAST:event_verEmpleadoActionPerformed

    private void actualizarListaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarListaEmpleadosActionPerformed
        actualizarListaEmpleadosAsignados();
    }//GEN-LAST:event_actualizarListaEmpleadosActionPerformed

    private void eliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpleadoActionPerformed
        if(listaEmpleadosAsignados.getSelectedIndex() > -1) {
            JFramePrincipal.sistema.getEmpleado(JFramePrincipal.sistema.getProyecto(index).getEmpleado(listaEmpleadosAsignados.getSelectedIndex())).removeProyecto(JFramePrincipal.sistema.getProyecto(index));
            JFramePrincipal.sistema.getProyecto(index).removeEmpleado(listaEmpleadosAsignados.getSelectedIndex());
            actualizarListaEmpleadosAsignados();
        }
    }//GEN-LAST:event_eliminarEmpleadoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Empleados;
    private javax.swing.JButton actualizarListaEmpleados;
    private javax.swing.JLabel cambiosProyecto;
    private javax.swing.JTextArea descripcionProyecto;
    private javax.swing.JLabel descripcionProyecto_text;
    private javax.swing.JButton eliminarEmpleado;
    private javax.swing.JTabbedPane empleados;
    private javax.swing.JLabel empleadosAsignados_text;
    private javax.swing.JRadioButton estado0Proyecto;
    private javax.swing.JRadioButton estado1Proyecto;
    private javax.swing.ButtonGroup estadoProyecto;
    private javax.swing.JLabel estadoProyecto_text;
    private javax.swing.JButton guardarDescripcionProyecto;
    private javax.swing.JButton guardarNombreProyecto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaEmpleadosAsignados;
    private javax.swing.JTextField nombreProyecto;
    private javax.swing.JLabel nombreProyecto_text;
    private javax.swing.JPanel proyecto;
    private javax.swing.JButton verEmpleado;
    // End of variables declaration//GEN-END:variables

    private void actualizarListaEmpleadosAsignados() {
        listaEmpleadosAsignados.setModel(JFramePrincipal.sistema.getProyecto(index).getEmpleadoModel());
    }

}
