/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designbosco;

import static designbosco.JFramePrincipal.sistema;
import java.awt.Color;

/**
 *
 * @author Ezequiel Melogno
 */
public class JFrameProducto extends javax.swing.JFrame {
    
    static int index;
    
    public JFrameProducto(int index) {
        initComponents();
        JFrameProducto.index = index;
        nombreProducto.setText(JFramePrincipal.sistema.getProducto(index).getNombre());
        precioProducto.setText(String.valueOf(JFramePrincipal.sistema.getProducto(index).getPrecio()));
        tipoProducto.setSelectedIndex(JFramePrincipal.sistema.getProducto(index).getTipo());
        descripcionProducto.setText(JFramePrincipal.sistema.getProducto(index).getDescripcion());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        descripcion_text = new javax.swing.JLabel();
        precioProducto = new javax.swing.JTextField();
        guardarDescripcion = new javax.swing.JButton();
        cambios_text = new javax.swing.JLabel();
        nombre_text = new javax.swing.JLabel();
        precio_text = new javax.swing.JLabel();
        tipo_text = new javax.swing.JLabel();
        guardarNombre = new javax.swing.JButton();
        guardarPrecio = new javax.swing.JButton();
        guardarTipo = new javax.swing.JButton();
        nombreProducto = new javax.swing.JTextField();
        tipoProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionProducto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(JFramePrincipal.sistema.getProducto(index).getNombre());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descripcion_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        descripcion_text.setText("Descripcion:");
        jPanel1.add(descripcion_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        precioProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(precioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 310, -1));

        guardarDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        guardarDescripcion.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarDescripcion.setText("Guardar");
        guardarDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(guardarDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 22));

        cambios_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cambios_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cambios_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 510, 50));

        nombre_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nombre_text.setText("Nombre: ");
        jPanel1.add(nombre_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        precio_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        precio_text.setText("Precio:");
        jPanel1.add(precio_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        tipo_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tipo_text.setText("Tipo:");
        jPanel1.add(tipo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        guardarNombre.setBackground(new java.awt.Color(255, 255, 255));
        guardarNombre.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarNombre.setText("Guardar");
        guardarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(guardarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 22));

        guardarPrecio.setBackground(new java.awt.Color(255, 255, 255));
        guardarPrecio.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarPrecio.setText("Guardar");
        guardarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(guardarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, 22));

        guardarTipo.setBackground(new java.awt.Color(255, 255, 255));
        guardarTipo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarTipo.setText("Guardar");
        guardarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTipoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, 22));

        nombreProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 310, -1));

        tipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Elije un tipo de proyecto*", "Diseno pagina web", "Desarrollo de aplicacion", "Otro" }));
        jPanel1.add(tipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 310, -1));

        descripcionProducto.setColumns(20);
        descripcionProducto.setRows(5);
        jScrollPane1.setViewportView(descripcionProducto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 300, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guardarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTipoActionPerformed
        if (tipoProducto.getSelectedIndex() == 0) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El producto tiene que tener un tipo.");
        } else {
            JFramePrincipal.sistema.getProducto(index).setTipo(tipoProducto.getSelectedIndex());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Tipo cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarTipoActionPerformed

    private void guardarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPrecioActionPerformed
        if(precioProducto.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El precio no puede estar en blanco.");
        } else if (!JFramePrincipal.chequearSiEsEntero(precioProducto.getText())) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El precio tiene que ser un entero.");
        } else {
            JFramePrincipal.sistema.getProducto(index).setPrecio(Integer.valueOf(precioProducto.getText()));
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Precio cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarPrecioActionPerformed

    private void guardarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarNombreActionPerformed
        if(nombreProducto.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El nommbre no puede estar en blanco.");
        } else if(JFramePrincipal.sistema.verificarProducto(nombreProducto.getText())) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("Este producto ya existe.");
        } else {
            JFramePrincipal.sistema.getProducto(index).setNombre(nombreProducto.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Nombre cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarNombreActionPerformed

    private void guardarDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDescripcionActionPerformed
        if(descripcionProducto.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("La descripcion no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getProducto(index).setDescripcion(descripcionProducto.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Descripcion cambiada satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarDescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cambios_text;
    private javax.swing.JTextArea descripcionProducto;
    private javax.swing.JLabel descripcion_text;
    private javax.swing.JButton guardarDescripcion;
    private javax.swing.JButton guardarNombre;
    private javax.swing.JButton guardarPrecio;
    private javax.swing.JButton guardarTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JLabel nombre_text;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JLabel precio_text;
    private javax.swing.JComboBox<String> tipoProducto;
    private javax.swing.JLabel tipo_text;
    // End of variables declaration//GEN-END:variables
}
