/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designbosco;

import static designbosco.JFramePrincipal.sistema;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ezequiel Melogno
 */
public class JFrameBuscarLocal extends javax.swing.JFrame {
    
    public JFrameBuscarLocal() {
        initComponents();
        actualizarListaLocales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cambios_text = new javax.swing.JLabel();
        departamento_text = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaLocales = new javax.swing.JList<>();
        buscarLocal = new javax.swing.JButton();
        ciudad_text = new javax.swing.JLabel();
        direccion_text = new javax.swing.JLabel();
        ciudadLocal = new javax.swing.JTextField();
        direccionLocal = new javax.swing.JTextField();
        departamentoLocal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Local");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cambios_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cambios_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cambios_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 510, 50));

        departamento_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        departamento_text.setText("Departamento: ");
        jPanel1.add(departamento_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jScrollPane2.setViewportView(listaLocales);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 400, 360));

        buscarLocal.setBackground(new java.awt.Color(255, 255, 255));
        buscarLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        buscarLocal.setText("Buscar");
        buscarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLocalActionPerformed(evt);
            }
        });
        jPanel1.add(buscarLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 170, 50));

        ciudad_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        ciudad_text.setText("Ciudad:");
        jPanel1.add(ciudad_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        direccion_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        direccion_text.setText("Direccion:");
        jPanel1.add(direccion_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        ciudadLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(ciudadLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 270, -1));

        direccionLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(direccionLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 270, -1));

        departamentoLocal.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        departamentoLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Cualquiera*", "Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", "Flores", "Florida", "Lavalleja", "Maldonado", "Montevideo", "Paysandu", "Rio Negro", "Rivera", "Rocha", "Salto", "San Jose", "Soriano", "Tacuarembo", "Treinta y Tres" }));
        jPanel1.add(departamentoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLocalActionPerformed
        actualizarListaLocales();
    }//GEN-LAST:event_buscarLocalActionPerformed

    public void actualizarListaLocales() {
        DefaultListModel lista = new DefaultListModel();
        ArrayList<Integer> listaIndex = sistema.buscarLocal(departamentoLocal.getSelectedIndex(), ciudadLocal.getText(), direccionLocal.getText());
        for(int i = 0;i < listaIndex.size();i++) {
            lista.addElement(sistema.getLocal(listaIndex.get(i)));
        }
        listaLocales.setModel(lista);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarLocal;
    private javax.swing.JLabel cambios_text;
    private javax.swing.JTextField ciudadLocal;
    private javax.swing.JLabel ciudad_text;
    private javax.swing.JComboBox<String> departamentoLocal;
    private javax.swing.JLabel departamento_text;
    private javax.swing.JTextField direccionLocal;
    private javax.swing.JLabel direccion_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaLocales;
    // End of variables declaration//GEN-END:variables
}
