/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designbosco;

import static designbosco.JFramePrincipal.sistema;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ezequiel Melogno
 */
public class JFrameBuscarProducto extends javax.swing.JFrame {
    
    public JFrameBuscarProducto() {
        initComponents();
        actualizarListaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cambios_text = new javax.swing.JLabel();
        nombre_text = new javax.swing.JLabel();
        tipo_text = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        tipoProducto = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        buscarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar producto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cambios_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cambios_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cambios_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 510, 50));

        nombre_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nombre_text.setText("Nombre: ");
        jPanel1.add(nombre_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tipo_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tipo_text.setText("Tipo:");
        jPanel1.add(tipo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        nombreProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(nombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 310, -1));

        tipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Cualquiera*", "Diseno pagina web", "Desarrollo de aplicacion", "Otro" }));
        jPanel1.add(tipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 310, -1));

        jScrollPane2.setViewportView(listaProductos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 400, 390));

        buscarProducto.setBackground(new java.awt.Color(255, 255, 255));
        buscarProducto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        buscarProducto.setText("Buscar");
        buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(buscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoActionPerformed
        actualizarListaProductos();
    }//GEN-LAST:event_buscarProductoActionPerformed

    public void actualizarListaProductos() {
        DefaultListModel lista = new DefaultListModel();
        ArrayList<Integer> listaIndex = sistema.buscarProducto(nombreProducto.getText(), tipoProducto.getSelectedIndex());
        for(int i = 0;i < listaIndex.size();i++) {
            lista.addElement(sistema.getProducto(listaIndex.get(i)));
        }
        listaProductos.setModel(lista);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarProducto;
    private javax.swing.JLabel cambios_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JLabel nombre_text;
    private javax.swing.JComboBox<String> tipoProducto;
    private javax.swing.JLabel tipo_text;
    // End of variables declaration//GEN-END:variables
}
