/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package designbosco;

import java.awt.Color;

/**
 *
 * @author Ezequiel Melogno
 */
public class JFrameEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCliente
     */
    
    static int indexLocal;
    static int indexEmpleado;
    
    public JFrameEmpleado(int indexLocal, int indexEmpleado) {
        initComponents();
        JFrameEmpleado.indexLocal = indexLocal;
        JFrameEmpleado.indexEmpleado = indexEmpleado;
        nombreEmpleado.setText(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getNombre());
        apellidoEmpleado.setText(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getApellido());
        ciEmpleado.setText(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getCi());
        telefonoEmpleado.setText(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getTelefono());
        cargoEmpleado.setText(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getCargo());
        correoEmpleado.setText(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getCorreo());
        actualizarListaProyectosAsignados();
        actualizarListaProyectos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        proyectosAsignados_text = new javax.swing.JLabel();
        nombreEmpleado = new javax.swing.JTextField();
        guardarNombre = new javax.swing.JButton();
        apellido_text = new javax.swing.JLabel();
        apellidoEmpleado = new javax.swing.JTextField();
        guardarApellido = new javax.swing.JButton();
        ciEmpleado = new javax.swing.JTextField();
        guardarCi = new javax.swing.JButton();
        ci_text = new javax.swing.JLabel();
        guardarTelefono = new javax.swing.JButton();
        telefono_text = new javax.swing.JLabel();
        telefonoEmpleado = new javax.swing.JTextField();
        correo_text = new javax.swing.JLabel();
        guardarCorreo = new javax.swing.JButton();
        correoEmpleado = new javax.swing.JTextField();
        asignarProyecto_text = new javax.swing.JLabel();
        correo_text1 = new javax.swing.JLabel();
        cargoEmpleado = new javax.swing.JTextField();
        guardarCargo = new javax.swing.JButton();
        nombre_text1 = new javax.swing.JLabel();
        proyectos = new javax.swing.JComboBox<>();
        asignarProyecto = new javax.swing.JButton();
        proyecto_text = new javax.swing.JLabel();
        listaProyectosAsignadosContainer = new javax.swing.JScrollPane();
        listaProyectosAsignados = new javax.swing.JList<>();
        editarProyecto = new javax.swing.JButton();
        actualizarListaProyectosAsignados = new javax.swing.JButton();
        desasignarProyecto = new javax.swing.JButton();
        verProyecto = new javax.swing.JButton();
        cambios_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).toString());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proyectosAsignados_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        proyectosAsignados_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proyectosAsignados_text.setText("Proyectos asignados");
        jPanel1.add(proyectosAsignados_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 230, 30));

        nombreEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(nombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 309, 20));

        guardarNombre.setBackground(new java.awt.Color(255, 255, 255));
        guardarNombre.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarNombre.setText("Guardar");
        guardarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(guardarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 22));

        apellido_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        apellido_text.setText("Apellido:");
        jPanel1.add(apellido_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 22));

        apellidoEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(apellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 309, -1));

        guardarApellido.setBackground(new java.awt.Color(255, 255, 255));
        guardarApellido.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarApellido.setText("Guardar");
        guardarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, 22));

        ciEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(ciEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 309, -1));

        guardarCi.setBackground(new java.awt.Color(255, 255, 255));
        guardarCi.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarCi.setText("Guardar");
        guardarCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCiActionPerformed(evt);
            }
        });
        jPanel1.add(guardarCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, 22));

        ci_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        ci_text.setText("CI:");
        jPanel1.add(ci_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 22));

        guardarTelefono.setBackground(new java.awt.Color(255, 255, 255));
        guardarTelefono.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarTelefono.setText("Guardar");
        guardarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 22));

        telefono_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        telefono_text.setText("Telefono:");
        jPanel1.add(telefono_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 22));

        telefonoEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        telefonoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(telefonoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 309, -1));

        correo_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        correo_text.setText("EMail:");
        jPanel1.add(correo_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 22));

        guardarCorreo.setBackground(new java.awt.Color(255, 255, 255));
        guardarCorreo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarCorreo.setText("Guardar");
        guardarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 22));

        correoEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(correoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 309, -1));

        asignarProyecto_text.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        asignarProyecto_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(asignarProyecto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 210, 40));

        correo_text1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        correo_text1.setText("Cargo:");
        jPanel1.add(correo_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 22));

        cargoEmpleado.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel1.add(cargoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 309, -1));

        guardarCargo.setBackground(new java.awt.Color(255, 255, 255));
        guardarCargo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        guardarCargo.setText("Guardar");
        guardarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCargoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, 22));

        nombre_text1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nombre_text1.setText("Nombre: ");
        jPanel1.add(nombre_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        proyectos.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        proyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proyectosActionPerformed(evt);
            }
        });
        jPanel1.add(proyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 20));

        asignarProyecto.setBackground(new java.awt.Color(255, 255, 255));
        asignarProyecto.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        asignarProyecto.setText("Asignar");
        asignarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(asignarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, -1));

        proyecto_text.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        proyecto_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proyecto_text.setText("Asignar a proyecto");
        jPanel1.add(proyecto_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, 30));

        listaProyectosAsignadosContainer.setViewportView(listaProyectosAsignados);

        jPanel1.add(listaProyectosAsignadosContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 230, 360));

        editarProyecto.setBackground(new java.awt.Color(255, 255, 255));
        editarProyecto.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        editarProyecto.setText("Editar");
        editarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(editarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 110, -1));

        actualizarListaProyectosAsignados.setBackground(new java.awt.Color(255, 255, 255));
        actualizarListaProyectosAsignados.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        actualizarListaProyectosAsignados.setText("Actualizar");
        actualizarListaProyectosAsignados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarListaProyectosAsignadosActionPerformed(evt);
            }
        });
        jPanel1.add(actualizarListaProyectosAsignados, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 640, 110, -1));

        desasignarProyecto.setBackground(new java.awt.Color(255, 255, 255));
        desasignarProyecto.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        desasignarProyecto.setText("Des-asignar");
        desasignarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desasignarProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(desasignarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 110, -1));

        verProyecto.setBackground(new java.awt.Color(255, 255, 255));
        verProyecto.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        verProyecto.setText("Ver");
        verProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(verProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 110, -1));

        cambios_text.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cambios_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cambios_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 488, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoEmpleadoActionPerformed

    private void guardarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarNombreActionPerformed
        if(nombreEmpleado.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El nombre no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).setNombre(nombreEmpleado.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Nombre cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarNombreActionPerformed

    private void guardarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarApellidoActionPerformed
        if(apellidoEmpleado.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El apellido no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).setApellido(apellidoEmpleado.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Apellido cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarApellidoActionPerformed

    private void guardarCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCiActionPerformed
        if(ciEmpleado.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("La cedula de identidad no puede estar en blanco.");
        } else if(JFramePrincipal.sistema.getLocal(indexLocal).verificarEmpleado(ciEmpleado.getText())) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("Este empleado ya existe.");
        } else {
            JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).setCi(ciEmpleado.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Cedula de identidad cambiada satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarCiActionPerformed

    private void guardarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTelefonoActionPerformed
        if(telefonoEmpleado.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El telefono no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).setTelefono(ciEmpleado.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Telefono cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarTelefonoActionPerformed

    private void guardarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCorreoActionPerformed
        if(correoEmpleado.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El correo electronico no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).setCorreo(correoEmpleado.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Correo electronico cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarCorreoActionPerformed

    private void guardarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCargoActionPerformed
        if(correoEmpleado.getText().isBlank()) {
            cambios_text.setForeground(Color.RED);
            cambios_text.setText("El cargo no puede estar en blanco.");
        } else {
            JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).setCargo(cargoEmpleado.getText());
            cambios_text.setForeground(Color.BLACK);
            cambios_text.setText("Cargo cambiado satisfactoriamente.");
        }
    }//GEN-LAST:event_guardarCargoActionPerformed

    private void proyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proyectosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proyectosActionPerformed

    private void editarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProyectoActionPerformed
        if( listaProyectosAsignados.getSelectedIndex() > -1 ) {
            new JFrameProyecto(JFramePrincipal.sistema.getIndexProyecto(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getProyecto(listaProyectosAsignados.getSelectedIndex()))).setVisible(true);
        }
    }//GEN-LAST:event_editarProyectoActionPerformed

    private void desasignarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desasignarProyectoActionPerformed
        if( listaProyectosAsignados.getSelectedIndex() > -1 ) {
            JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).removeProyecto(listaProyectosAsignados.getSelectedIndex());
            JFramePrincipal.sistema.getProyecto(proyectos.getSelectedIndex()).removeEmpleado(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado));
            actualizarListaProyectosAsignados();
        }
    }//GEN-LAST:event_desasignarProyectoActionPerformed

    private void verProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProyectoActionPerformed
        if( listaProyectosAsignados.getSelectedIndex() > -1 ) {
            new JFrameProyecto(JFramePrincipal.sistema.getIndexProyecto(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getProyecto(listaProyectosAsignados.getSelectedIndex()))).setVisible(true);
        }
    }//GEN-LAST:event_verProyectoActionPerformed

    private void asignarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarProyectoActionPerformed
        if (JFramePrincipal.sistema.getProyectos().size() < 1) {
            asignarProyecto_text.setForeground(Color.RED);
            asignarProyecto_text.setText("Este proyecto no existe.");
        } else if(verificarProyecto(JFramePrincipal.sistema.getProyectos().get(proyectos.getSelectedIndex()))) {
            asignarProyecto_text.setForeground(Color.RED);
            asignarProyecto_text.setText("Este proyecto ya esta asignado.");
        } else {
            JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).addProyecto(JFramePrincipal.sistema.getProyectos().get(proyectos.getSelectedIndex()));
            JFramePrincipal.sistema.getProyecto(proyectos.getSelectedIndex()).addEmpleado(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado));
            actualizarListaProyectosAsignados();
            asignarProyecto_text.setForeground(Color.BLACK);
            asignarProyecto_text.setText("Proyecto asignado con exito.");
        }
    }//GEN-LAST:event_asignarProyectoActionPerformed

    private void actualizarListaProyectosAsignadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarListaProyectosAsignadosActionPerformed
        actualizarListaProyectosAsignados();
    }//GEN-LAST:event_actualizarListaProyectosAsignadosActionPerformed

    public boolean verificarProyecto(Proyecto proyecto) { // si el proyecto ya esta asignado a ese empleado da 1
        boolean check = false;
        for(int i = 0;i < JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getProyecto().size();i++) {
            if(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getProyecto(i).equals(proyecto)) {
                check = true;
            }
        }
        return check;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarListaProyectosAsignados;
    private javax.swing.JTextField apellidoEmpleado;
    private javax.swing.JLabel apellido_text;
    private javax.swing.JButton asignarProyecto;
    private javax.swing.JLabel asignarProyecto_text;
    private javax.swing.JLabel cambios_text;
    private javax.swing.JTextField cargoEmpleado;
    private javax.swing.JTextField ciEmpleado;
    private javax.swing.JLabel ci_text;
    private javax.swing.JTextField correoEmpleado;
    private javax.swing.JLabel correo_text;
    private javax.swing.JLabel correo_text1;
    private javax.swing.JButton desasignarProyecto;
    private javax.swing.JButton editarProyecto;
    private javax.swing.JButton guardarApellido;
    private javax.swing.JButton guardarCargo;
    private javax.swing.JButton guardarCi;
    private javax.swing.JButton guardarCorreo;
    private javax.swing.JButton guardarNombre;
    private javax.swing.JButton guardarTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList<String> listaProyectosAsignados;
    private javax.swing.JScrollPane listaProyectosAsignadosContainer;
    private javax.swing.JTextField nombreEmpleado;
    private javax.swing.JLabel nombre_text1;
    private javax.swing.JLabel proyecto_text;
    private javax.swing.JComboBox<String> proyectos;
    private javax.swing.JLabel proyectosAsignados_text;
    private javax.swing.JTextField telefonoEmpleado;
    private javax.swing.JLabel telefono_text;
    private javax.swing.JButton verProyecto;
    // End of variables declaration//GEN-END:variables

    private void actualizarListaProyectosAsignados() {
        listaProyectosAsignados.setModel(JFramePrincipal.sistema.getLocal(indexLocal).getEmpleado(indexEmpleado).getProyectoModel());
    }
    
    private void actualizarListaProyectos() {
        proyectos.setModel(JFramePrincipal.sistema.getProyectoComboBoxModel());
    }
}
